# -*- coding: utf-8 -*-
"""Conll Test QA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x_CZ95skIi2N8ThLcn5hsdAiPg0-OfcM
"""

!pip install openai

import openai
from openai import OpenAI

import json

SYSTEM_PROMPT = "You are a smart and intelligent Named Entity Recognition (NER) system. I will provide you with a question including the entity type and entity definition and the sentence to extract entities from. The output should be formatted as a list of the extracted entities separated by commas with no additional text. Do not provide additional context in your answer."

USER_PROMPT_1 = "Are you clear about your role?"

ASSISTANT_PROMPT_1 = "Sure, I'm ready to help you with your NER task. Please provide me with the necessary information to get started."

PROMPT = (
    "Entity Definition:\n"
    "1. PER: Short name or full name of a person from any geographic regions.\n"
    "2. LOC: Name of any geographic location, like cities, countries, continents, districts etc.\n"
    "3. ORG: Name of the companies like Google, Samsung, Apple etc.\n"
    "4. MISC: Miscellaneous entities which do not belong to the previous groups.\n"
    "\n"
    "Output Format:\n"
    "{\"PER\": [list of entities present], \"LOC\": [list of entities present],\"ORG\": [list of entities present],\"MISC\": [list of entities present]}\n"
    "If no entities are presented in any categories, simply return {}\n"
    "\n"
    "Examples:\n"
    "\n"
    "1. Sentence: EU rejects German call to boycott British lamb .\n"
    "Output: {\"PER\": [], \"ORG\": [\"EU\"], \"LOC\": [], \"MISC\": [\"German\", \"British\"]}\n"
    "\n"
    "2. Sentence: The European Commission said on Thursday it disagreed with German advice to consumers to shun British lamb until scientists determine whether mad cow disease can be transmitted to sheep .\n"
    "Output: {\"PER\": [], \"ORG\": [\"European Commission\"], \"LOC\": [], \"MISC\": [\"German\", \"British\"]}\n"
    "\n"
    "3. Sentence: Germany 's representative to the European Union 's veterinary committee Werner Zwingmann said on Wednesday consumers should buy sheepmeat from countries other than Britain until the scientific advice was clearer .\n"
    "Output: "
)

def generate_qa_prompt(sentence, entity, definition):
  prompt = ""
  #prompt += "Entity Definitions:\n1. PER: Short name or full name of a single individual person, but not a group of people.\n2. LOC: Name of any geographic physical location, like city or country names.\n3. ORG: Name of any organization or governing body or companies like Google, Samsung, Apple etc.\n4. MISC: Miscellaneous entities which do not belong to the previous groups.\n"
  prompt += "Entity Definitions:\n1. corporation: Indicates named entities associated with corporations, companies or businesses.\n2. creative-work: Represents named entities related to creative works, such as books, movies, or songs.\n3. group: Indicates named entities associated with groups or organizations.\n4. location: Represents named entities related to locations or places.\n5. person: Denotes named entities referring to individuals or people.\n6. product: Denotes named entities associated with products or items.\n"
  #prompt += entity+ " entities are defined as "+definition+" In the following sentence, which entities can be labled as "+entity+"? If there are none, output only 'None' with no additional text or punctuation."
  prompt += "In the following sentence, which entities can be labled as "+entity+"? If there are none, output only 'None' with no additional text or punctuation."
  prompt += "\n\nSentence:\n"+sentence+"\n"

  return prompt

def mask_sentence(sentence, entitytype, entities):
  masked_sentence = sentence
  for i in range(len(entities)):
    #mask = "<"+chr(65+i)+"-"+entitytype+">"
    mask = "."
    masked_sentence = masked_sentence.replace(entities[i],mask)
  #print(masked_sentence)
  return masked_sentence

generate_qa_prompt("Germany 's representative to the European Union 's veterinary committee Werner Zwingmann said on Wednesday consumers should buy sheepmeat from countries other than Britain until the scientific advice was clearer .","PER", "Short name or full name of a person from any geographic regions.")

client = OpenAI(
    # defaults to os.environ.get("OPENAI_API_KEY")
    api_key="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",

)
def openai_chat_completion_response(sentence, entities, definition):
  responses = {}
  for i in range(len(entities)):
    final_prompt = generate_qa_prompt(sentence, entities[i],definition[i])
    response = client.chat.completions.create(
                model="gpt-3.5-turbo",
                temperature=0,
                messages=[
                      {"role": "system", "content": SYSTEM_PROMPT},
                      {"role": "user", "content": USER_PROMPT_1},
                      {"role": "assistant", "content": ASSISTANT_PROMPT_1},
                      {"role": "user", "content": final_prompt}
                  ]
              )
    text = vars(vars(vars(response)['choices'][0])['message'])['content'].strip()
    if text == "None":
      responses[entities[i]] = []
    else:
      responses[entities[i]] = text.split(", ")
      sentence = mask_sentence(sentence, entities[i], text.split(", "))
  return responses

#{"PER": ["Werner Zwingmann"], "ORG": ["European Union"], "LOC": ["Germany", "Britain"], "MISC": []}

entities = ["PER", "ORG", "LOC", "MISC"]
definitions = ["Short name or full name of a single individual person, but not a group of people.",
    "Name of any organization or governing body or companies like Google, Samsung, Apple etc.",
    "Name of any geographic physical location, like city or country names.",
    "Miscellaneous proper named specific entities that are not persons or locations or organizations"]
sentence = "Germany 's representative to the European Union 's veterinary committee Werner Zwingmann said on Wednesday consumers should buy sheepmeat from countries other than Britain until the scientific advice was clearer ."
sentence = "The European Commission said on Thursday it disagreed with German advice to consumers to shun British lamb until scientists determine whether mad cow disease can be transmitted to sheep ."
#promptList = generate_qa_sequence(sentence, entities, definitions)

ners = openai_chat_completion_response(sentence, entities, definitions)
print(ners)

test_data = None

with open('conll_test.json', 'r') as infile:
  test_data = json.load(infile)

from tqdm import tqdm

tags = test_data["tags"]
input_data = test_data["sentences"]
length = len(input_data)
print(length)

#example_data = train_data["sentences"]

prompt = None
answer = None

qa_zero_shot_test = {"predictions":[], "labels":[]}

client = OpenAI(
    # defaults to os.environ.get("OPENAI_API_KEY")
    api_key="",

)

entities = ["PER", "ORG", "LOC", "MISC"]
definitions = ["Short name or full name of a single individual person, but not a group of people.",
    "Name of any organization or governing body or companies like Google, Samsung, Apple etc.",
    "Name of any geographic physical location, like city or country names.",
    "Miscellaneous proper named specific entities that are not persons or locations or organizations"]


for i in tqdm(range(length)):
  input = input_data[i]["sentence"]
  output = input_data[i]["ner_sentence"]
  try:
    response = openai_chat_completion_response(input, entities, definitions)
    qa_zero_shot_test["predictions"].append(response)
    qa_zero_shot_test["labels"].append(answer)

  except:
    pass

test_data = None

with open('wnut_test.json', 'r') as infile:
  test_data = json.load(infile)
tags = test_data["tags"]
input_data = test_data["sentences"]
length = len(input_data)
print(length)

from tqdm import tqdm

#example_data = train_data["sentences"]

prompt = None
answer = None

qa_zero_shot_test = {"predictions":[], "labels":[]}

client = OpenAI(
    # defaults to os.environ.get("OPENAI_API_KEY")
    api_key="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",

)

entities = ["corporation", "creative-work", "group", "location", "person","product"]
definitions = ["Indicates named entities associated with corporations, companies or businesses.",
    "Represents named entities related to creative works, such as books, movies, or songs.",
    "Indicates named entities associated with groups or organizations.",
    "Represents named entities related to locations or places.",
    "Denotes named entities referring to individuals or people.",
    "Denotes named entities associated with products or items."]


for i in tqdm(range(length)):
  input = input_data[i]["sentence"]
  output = input_data[i]["ner_sentence"]
  try:
    response = openai_chat_completion_response(input, entities, definitions)
    qa_zero_shot_test["predictions"].append(response)
    qa_zero_shot_test["labels"].append(answer)

  except:
    pass

with open("qa_zero_shot_test.json", "w") as outfile:
  json.dump(qa_zero_shot_test, outfile)

qa_zero_shot_test["labels"] = []
for i in tqdm(range(100)):
  output = input_data[i]["entities"]
  qa_zero_shot_test["labels"].append(output)
